# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaintype',
            new_name='complaintType',
        ),
    ]
