# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 03:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_auto_20171022_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateField(verbose_name=datetime.date),
        ),
    ]
