# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_auto_20171023_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='commune',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(default=b'Reportada', max_length=100),
        ),
    ]
