# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 04:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='static/img/')),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('arrival', models.DateField(default=datetime.date.today, null=True)),
                ('adopted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.TypeAnimal'),
        ),
    ]
