# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 21:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='adopted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='arrival',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='picture',
            field=models.ImageField(upload_to=b''),
        ),
    ]
