# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 04:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ong_id', models.CharField(default='ong', max_length=10)),
                ('animal_id', models.CharField(max_length=50)),
                ('person_id', models.CharField(max_length=50)),
                ('arrival', models.DateField(default=datetime.date.today, null=True)),
                ('departure', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
