# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='ong_id',
            field=models.CharField(default=b'ong', max_length=10),
        ),
    ]
